---

- include: mac.yml
  when: ansible_distribution == "MacOSX"
  tags: hg-install

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: hg-install

- include: config.yml
  tags: hg-config
